version: 0.2
env:
  variables:
    S3_BUCKET: "deskbucket1.0"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist/onlineTest'
  discard-paths: yes
